remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: "Bubble Bobble - Quilmo Studios"
description: "This project is a tribute to the game Bubble Bobble, released in Japan in 1986 by Taito Corporation."

github:
  repository_url: https://github.com/mxarc
  repository_url: https://github.com/Vequi
